### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() 

### ISSUE THREAD

**Issue by q5390498** [LibOPF/LibOPF#5]
```lang=python
from libopf_py import OPF
from sklearn import datasets, metrics
import numpy as np

digits = datasets.load_digits()


n_samples = len(digits.images)
data  = digits.images.reshape((n_samples, -1))
label = digits.target.astype(np.int32)
# print(data.shape)
#Let's split our dataset in the training and testing parts
rand = np.random.permutation(n_samples)

#half data for traning, other half for testing
n_split = int(n_samples/2)
print(n_split)

data_train,  data_test  = data[rand][:n_split], data[rand][n_split:]
label_train, label_test = label[rand][:n_split], label[rand][n_split:]

# print(data_train.shape, label_train.reshape(n_split, -1))
O = OPF()
O.fit(np.array(data_train[:2]), np.array(label_train[:2]))
predicted = O.predict(data_test)

print("Classification report for OPF:\n%s\n" % (metrics.classification_report(label_test, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(label_test, predicted))
```
I ran through the above code and encountered the following mistakes. How can I solve them?
```lang=sh
$ python opf_test.py                                                                                                                                                                          │data_disk         NVIDIA_CUDA-8.0_Samples      share
898                                                                                                                                                                                           │FycmF5KGxhYmVsX3RyYWluWzoyXSkpCiAgRmlsZSAibGlib3BmX3B5LnB5eCIsIGxpbmUgNzTraceback (most recent call last):                                                                                                                                                            │CgpCgo=ts         opencv-3.4.0                 Videos
  File "opf_test.py", line 24, in <module>                                                                                                                                                    │Downloads         opencv-3.4.0.zip             zyh
    O.fit(np.array(data_train[:2]), np.array(label_train[:2]))                                                                                                                                │examples.desktop  opencv-3.4.4
  File "libopf_py.pyx", line 75, in libopf_py.OPF.fit (libopf_py.c:1761)                                                                                                                      │get-pip.py        opencv_contrib-3.3.0
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() 
```

**Comment by kalleknast** [comment]
It is fixed in the pull request (working python3 examples; numpy 1.14+ cython fix;), however it hasn't been merged yet. 

The offending lines are lines 75 and 85 in libopf_py.pyx.
Original line 75:
     ```if Y != None:```
Replace with:
      ```if Y is not None:```
Original line 85:
      ```if Y != None and X.shape[0] != Y.shape[0]:```
replace with:
      ```if Y is not None and X.shape[0] != Y.shape[0]:```

You have 3 options:

1. Wait for the pull request to be merged (if ever)
2. Change the offending lines yourself
3. Use dhaalves' repo instead (https://github.com/dhaalves/LibOPF). It contains some other fixes and improvements too.

**Comment by q5390498** [comment]
thank you very much. I have sloved this problem by option 3.

**Comment by q5390498** [comment]
Is there any methed to predict the probability or distance ? @kalleknast  thank you very much.

**Comment by kalleknast** [comment]
I looked around a bit, but I don't think there is any of getting something that can be interpreted as probabilities. It might be possible to hack the code so that it returns the distance between a sample and a prototype, but I don't know if that distance would be meaningful.
